// Copyright 2022 Stefan Kerkmann
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define DEBUG_MATRIX_SCAN_RATE

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP25
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U

#define BACKLIGHT_PWM_DRIVER PWMD4
#define BACKLIGHT_PWM_CHANNEL RP2040_PWM_CHANNEL_B

// define AUDIO_PIN GP16
// define AUDIO_PWM_DRIVER PWMD0
// define AUDIO_PWM_CHANNEL RP2040_PWM_CHANNEL_A
//
// define ADC_PIN GP26

// PS2 mouse
#define PS2_CLOCK_PIN   GP16
#define PS2_DATA_PIN    GP17

